version: '3'
services:
  app:
    build: .
    expose:
      - "9000"
    environment:
      - BIND_ADDRESS=0.0.0.0
      - BIND_PORT=9000

  nginx:
    image: nginx:latest
    ports:
      - "90:90"
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt

volumes:
  certs:
  certs-data:
